#!/usr/bin/env python3
"""Generates src/unicode_tables.hpp from Python's Unicode database.

Two tables:

  kCombiningRanges  Mn/Me codepoint ranges -- characters that carry no width
                    of their own and attach to the preceding base character.

  kComposePairs     canonical (base, mark) -> precomposed codepoint, filtered
                    to the pairs NFC actually recomposes so that composition
                    exclusions are respected rather than hand-maintained.

Regenerate with:  python3 tools/gen_unicode_tables.py
The output is committed, so a build never depends on running this.
"""
import unicodedata

def combining_ranges():
    cats = [cp for cp in range(0x300, 0x110000)
            if unicodedata.category(chr(cp)) in ('Mn', 'Me')]
    runs = []
    for cp in cats:
        if runs and cp == runs[-1][1] + 1:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    return runs

def compose_pairs():
    out = []
    for cp in range(0x20, 0x110000):
        ch = chr(cp)
        d = unicodedata.decomposition(ch)
        if not d or '<' in d:
            continue
        parts = d.split()
        if len(parts) != 2:
            continue
        base, mark = int(parts[0], 16), int(parts[1], 16)
        # Only keep what NFC really recomposes: that filters out the
        # composition exclusions without needing the exclusion list.
        if unicodedata.normalize('NFC', chr(base) + chr(mark)) == ch:
            out.append((base, mark, cp))
    out.sort(key=lambda t: (t[0], t[1]))
    return out

ranges = combining_ranges()
pairs = compose_pairs()

with open('src/unicode_tables.hpp', 'w') as f:
    f.write("// Generated by tools/gen_unicode_tables.py -- do not edit by hand.\n")
    f.write("// Unicode %s\n#pragma once\n\n#include <cstdint>\n\n" % unicodedata.unidata_version)

    f.write("// Mn/Me ranges, inclusive, sorted. Characters here attach to the\n"
            "// preceding base character and occupy no column of their own.\n")
    f.write("struct CombiningRange { char32_t lo, hi; };\n")
    f.write("inline constexpr CombiningRange kCombiningRanges[] = {\n")
    for lo, hi in ranges:
        f.write("    {0x%04X, 0x%04X},\n" % (lo, hi))
    f.write("};\n")
    f.write("inline constexpr int kCombiningRangeCount = %d;\n\n" % len(ranges))

    # Block-level pre-filter. Combining marks are sparse and clustered, while
    # the hot path asks about CJK and emoji constantly -- both far from any
    # mark. One bit per 256-codepoint block turns those into a load and a test
    # instead of a binary search over every range.
    top = max(hi for lo, hi in ranges)
    nblocks = (top >> 8) + 1
    bits = bytearray((nblocks + 7) // 8)
    for lo, hi in ranges:
        for blk in range(lo >> 8, (hi >> 8) + 1):
            bits[blk >> 3] |= 1 << (blk & 7)
    f.write("// One bit per 256-codepoint block: set if the block contains any\n"
            "// Mn/Me character. Rejects the common non-mark cases immediately.\n")
    f.write("inline constexpr char32_t kCombiningMaxCodepoint = 0x%04X;\n" % top)
    f.write("inline constexpr uint8_t kCombiningBlockBits[] = {\n")
    for i in range(0, len(bits), 16):
        f.write("    " + " ".join("0x%02X," % b for b in bits[i:i+16]) + "\n")
    f.write("};\n\n")

    f.write("// Canonical compositions, sorted by (base, mark) for binary search.\n")
    f.write("struct ComposePair { char32_t base, mark, composed; };\n")
    f.write("inline constexpr ComposePair kComposePairs[] = {\n")
    for b, m, c in pairs:
        f.write("    {0x%04X, 0x%04X, 0x%04X},\n" % (b, m, c))
    f.write("};\n")
    f.write("inline constexpr int kComposePairCount = %d;\n" % len(pairs))

print("wrote src/unicode_tables.hpp: %d combining ranges, %d compose pairs"
      % (len(ranges), len(pairs)))
